service: csv-writer-task

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    CsvTaskTable: ${self:custom.CsvTaskTable.name}
  iamRoleStatements:
    - ${file(iam/CsvTaskTableIAM.yml):CsvTaskTableIAM}
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

resources:
  Resources:
    CsvTaskTable: ${file(resources/CsvTaskTable.yml):CsvTaskTable}
    
functions:
  processS3File:
    handler: src/handlers/processS3File.handler
    events:
      - s3:
          bucket: amit-s3-task-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
          existing: true
  getAllUsers:
    handler: src/handlers/getAllUsers.handler
    events:
      - http:
          method: GET
          path: /users

  getUserById:
    handler: src/handlers/getUserById.handler
    events:
      - http:
          method: GET
          path: /users/{id}

custom:
  CsvTaskTable:
    name: !Ref CsvTaskTable
    arn:  !GetAtt CsvTaskTable.Arn
