service: csv-writer-task

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::amit-s3-task-bucket/*"

functions:
  processS3File:
    handler: src/handler.processS3File
    events:
      - s3:
          bucket: amit-s3-task-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
          existing: true
